name: Deploy GitHub Pages And Gitee Pages
# 触发条件：在 push 到 master 分支后
on:
  push:
    branches:
      - master
jobs:
  # 构建并部署
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 拉取仓库代码
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      # 构建
      - name: Build
        # env:
        # 注意在 Settings->Secrets 配置 VSSUE_CLIENT_ID : OAuth Apps
        # VSSUEID: ${{ secrets.VSSUE_CLIENT_ID }}
        # VSSUESECRET: ${{ secrets.VSSUE_CLIENT_SECRET }}
        run: npm run build

      # 部署到分支
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.5.9
        with:
          # 注意在 Settings->Secrets 配置 ACCESS_TOKEN : Personal access tokens
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          # 需要部署的分支
          BRANCH: gh-pages
          # vue项目 build 目录
          FOLDER: .mineBlog/root

  # 同步 gitee 并 更新 giteepages
  sync-to-gitee:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      # 克隆项目至 gitee
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@v1.0.1
        env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY : id_rsa
          # 个人设置 -> SSH公钥 -> 上传公钥
          SSH_PRIVATE_KEY: ${{ secrets.mine7eleven@gmail.com }}
        with:
          # 注意替换为你的 GitHub 源仓库地址 SSH
          source-repo: 'git@gitee.com:xiangbin0712/blog.git'
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: 'git@gitee.com:xiangbin0712/blog.git'

      # 更新部署 gitee pages
      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@v1.1.3
        with:
          # 注意替换为你的 Gitee 用户名
          gitee-username: xiangbin0712
          # 注意在 Settings->Secrets 配置 GITEE_PASSWORD : gitee password
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          # 注意替换为你的 Gitee 仓库
          gitee-repo: xiangbin0712/blog
          # 构建分支
          branch: gh-pages
